name: Maven CI
on:
  push

env:
  maven_package_cache: ".m2/repository/"
  MAVEN_OPTS: "-Dmaven.repo.local=./$maven_package_cache"

jobs:
  build:
    runs-on: self-hosted
    steps:
      - uses: actions/cache@v2
        with:
          path: $maven_packages_cache
          key: ${{runner.os}}-build

      - uses: actions/checkout@v2

      - uses: actions/setup-java@v2
        with:
          java-version: '11'
          distribution: 'adopt'

      - name: Build with Maven
        run: mvn compile
      - uses: actions/upload-artifact@v2
        with:
          name: compile
          path: target

  test:
    needs:
      - build
    runs-on: self-hosted
    steps:
      - uses: actions/cache@v2
        with:
          path: $maven_packages_cache
          key: ${{runner.os}}-build

      - uses: actions/checkout@v2

      - uses: actions/setup-java@v2
        with:
          java-version: '11'
          distribution: 'adopt'

      - run: mvn test

  package:
    needs:
      - test
    runs-on: self-hosted
    steps:
      - uses: actions/cache@v2
        with:
          path: $maven_packages_cache
          key: ${{runner.os}}-build

      - uses: actions/checkout@v2

      - uses: actions/setup-java@v2
        with:
          java-version: '11'
          distribution: 'adopt'

      - run: mvn package
      - uses: actions/upload-artifact@v2
        with:
          name: war
          path: target/*.war

  deploy_test:
    needs:
      - package
    runs-on: self-hosted
    environment:
      name: Test Env
      url: http://localhost:8081/game2048
    steps:
      - name: Deploy War
        run: cp -f ./target/*.war /usr/local/tomcat/webapps